#include "DISTANCE_SENSOR_TASK.h"

void DISTANCE_SENSOR_TASK(void) {
    DISTANCE_SENSOR_MEASURE_CM(); 
}

void DISTANCE_SENSOR_MEASURE_MICROSSECONDS(void) {
    
}

void DISTANCE_SENSOR_MEASURE_CM(void) {

}