//PURPOSE: 
/*
* THIS IS A CODE IN C WHICH WILL BE RESPONSIBLE TO TABLE CARE OF ALL MICRO CONTROLLER INTERRUPTIONS
* AND WILL ACT AS A BUS EVENT CODE TO SEND THESE INTERRUPTIONS TO THEIR HANDLERS 
*/

#include <avr/io.h> 
#include <avr/interrupt.h>
#include "Modules/GLOBAL/ISRFunctionsCallback.h"

ISR(TIMER1_COMPA_vect) {
    LED_CALLBACK(); 
}

ISR(TIMER1_COMPB_vect) {
    BUZZER_CALLBACK(); 
}