#include "app.h"


void APP_SET_PINS() {
  
  SetPinAsInput(&DDRD, PD7); // THIS SHOULD BE A BUTTON 
  //SetPinAsOutput(&DDRB, PB5); // PB GREEN LED! 
  
  SetPinAsOutput(&DDRD, PD5); // THIS, PD3 AND PB3 SHOULD BE LEDS RED LED  
  SetPinAsOutput(&DDRD, PD4);
  SetPinAsOutput(&DDRD, PD6); // THIS MUST BE A BUZZER 
  SetPinAsOutput(&DDRD, PD3); // YELLOW LED 
  
  PutElectricity(&PORTD, PD7);
}

void APP_INIT() {
  APP_SET_PINS(); 
  SCHEDULER_INIT();
  LIGHT_SENSOR_INIT();   
  USART_INIT(); 
  BUZZER_DEFINE_TASK(BUZZER_FAST_BIP, 0, BUZZER_MODE_BIP);
  BUZZER_DEFINE_TASK(BUZZER_FAST_BIP, 1, BUZZER_MODE_BIP); 
}

void APP_TASK() {
  SCHEDULER_RUN();
}