#include "app.h"


void APP_SET_PINS() {
  SetPinAsOutput(&DDRD, BUTTON_CONTROLLED_RED_LED);
  SetPinAsOutput(&DDRD, BUTTON_CONTROLLED_GREEN_LED);
  SetPinAsOutput(&DDRD, BOT_CONTROLLED_LED); 
  SetPinAsOutput(&DDRD, COMMUNICATION_STATUS_LED);
  SetPinAsInput(&DDRB, BUTTON_PIN);

  SetPinAsOutput(&DDRD, BUZZER_PIN);  
  PutElectricity(&PORTD, BUZZER_PIN);
  PutElectricity(&PORTB, BUTTON_PIN);  

}

void APP_INIT() {
  APP_SET_PINS(); 
  SCHEDULER_INIT();
  LIGHT_SENSOR_INIT();   
  USART_INIT(); 
  BUZZER_DEFINE_TASK(BUZZER_FAST_BIP, 0, BUZZER_MODE_BIP);
  BUZZER_DEFINE_TASK(BUZZER_FAST_BIP, 1, BUZZER_MODE_BIP); 
}

void APP_TASK() {
  SCHEDULER_RUN();
}